# This file was generated by GoReleaser. DO NOT EDIT.
cask "speedtest" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0b32627d7796432e1ffcc72fc52ddf7e98049f2d80b77044c3def7d83339ec9b"
      url "https://github.com/victor-hucklenbroich/speedtest-cli/releases/download/v#{version}/speedtest-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1b8239abf494fe79fe8c9096e045b7baee66be526d910b659e99625a5b49a95"
      url "https://github.com/victor-hucklenbroich/speedtest-cli/releases/download/v#{version}/speedtest-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6581231012d5ffa709d48d3897266db591610e5f31575c800e2d3fa587776315"
      url "https://github.com/victor-hucklenbroich/speedtest-cli/releases/download/v#{version}/speedtest-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d10076d961e277837f6c3ef422269394b0e7b9f4b4874e7cfe0c80bfffecc12"
      url "https://github.com/victor-hucklenbroich/speedtest-cli/releases/download/v#{version}/speedtest-cli_linux_arm64.tar.gz"
    end
  end

  name "speedtest"
  desc "Terminal internet speed test with an animated TUI"
  homepage "https://github.com/victor-hucklenbroich/speedtest-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speedtest"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/speedtest"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `speedtest` for a full test, `speedtest --help` for options.
  EOS
end
